project:
  type: website

website:
  title: "Yichen Liu's Homepage"
  navbar:
    pinned: true
    left:
      - text: "About Me"
        file: intro.qmd
      - text: "CV"
        file: Yichen_Liu_ds.pdf
      # - text: "Project and Research"
      #   file: 
      # - text: "Workflows"
      #   file: workflow.qmd
      # - text: "Learn more"
      #   file: learn-more.qmd
    # right:
    #   - icon: github
    #     href: 
    page-navigation: true

format:
  html:
    theme: [litera, styles.scss]
    css: styles.scss
    highlight-style: tango

editor: source

